config/routes.rb
TutoApp::Application.routes.draw do
  get "users/new"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "sessions/new"
  get "sessions/destroy"
  
  match '/help',    :to => 'static_pages#help',    :via => 'get'
  match '/about',   :to => 'static_pages#about',   :via => 'get'
  match '/contact', :to =>'static_pages#contact',  :via =>'get'
  match '/signup',  :to =>'users#new',       :via =>'get'
  match '/signin', :to => 'sessions#new', :via => 'get'
  match '/signout', :to => 'sessions#destroy', :via => 'get'

  resources :microposts

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root 'static_pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	validates :content , :length => { :maximum => 140}
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :microposts

before_save { self.email = email.downcase }
before_create :create_remember_token

validates :name, :presence => true , :length => {:maximum => 50}
validates :email, :presence => true 
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email , :presence => true,  :uniqueness => { :case_sensitive => false } ,:format => {:with => VALID_EMAIL_REGEX } 
has_secure_password
validates :password, :length => { :minimum => 6 }

def User.new_remember_token
	SecureRandom.urlsafe_base64
end
def User.encrypt(token)
	Digest::SHA1.hexdigest(token.to_s)
end

private 
def create_remember_token
	self.remember_token = User.encrypt(User.new_remember_token)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @micropost }
      else
        format.html { render action: 'new' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
	
end

def create
    user = User.find_by(:email => params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  def contact
  end
  def about
  end
end

app/controllers/users_controller.rb
# encoding: utf-8

class UsersController < ApplicationController

  before_action :signed_in_user, :only => [:index,:edit, :update, :destroy]
  before_action :correct_user ,  :only => [:edit, :update]
  
def index
    @users = User.all
end
def edit
  @user = User.find(params[:id])
end
 
 def update
  @user = User.find(params[:id])
  if @user.update_attributes(user_params)
    flash[:success] = "Profil actualisé."
      redirect_to @user
  else
    render 'edit'
  end
   
 end

  def new
  	@user = User.new
  end
  
  def show
  	@user = User.find(params[:id])	
  end



def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end


  def destroy
     User.find(params[:id]).destroy    
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private 
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	
  end
def signed_in_user
  redirect_to signin_url, :notice => "Please sign in " unless signed_in? 
end
 def correct_user
   @user = User.find(params[:id])
   redirect_to(root_url) unless current_user?(@user)
 end



 end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
def current_user?(user)
    user == current_user
  end


def signed_in?
    !current_user.nil?
 end

def current_user=(user)
    @current_user = user
  end
  # Trouver le current_user qui utilise le token_remember 
def current_user
	remember_token = User.encrypt(cookies[:remember_token])
	@current_user ||= User.find_by(:remember_token => remember_token)
	
end

def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end


  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
 		gravatar_url = "https://secure.gravatar.com/avatar/"#{gravatar_id}"    
    	image_tag(gravatar_url, :alt => user.name, :class => "gravatar")
    end
 end


 #
 #

app/views/layouts/_footer.html.erb
<nav style="margin-top: 170px;" class="top-bar" data-topbar="">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#"></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>

    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
         <li><a href="http://railstutorial.org/" title="">Rails Tutorial by Michael Hartl</a>

    </ul>
    </ul>
  </section>

  
</nav>

app/views/layouts/_header.html.erb
<nav style="margin-top: 9px;" class="top-bar" data-topbar="">

<!-- <nav class="top-bar" data-topbar> -->
  <ul class="title-area">
    <li class="name">
      <h1><a href="#"><%= link_to "Sample app", root_path, id: "logo" %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">

          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
           
           <% if signed_in? %>
              
              <li><%= link_to "Users", users_path %></li>
              
              <li> <%= link_to "Profile", user_path(current_user) %></li>
              
              
                  <li><%= link_to "Edite your Profile", edit_user_path(current_user) %></li>
                  

              </li>

            <li> <%= link_to "Sign out", signout_path, :method => "delete" %> </li>  
              
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
           <% end %>
  </ul>

    <!-- Left Nav Section -->
    <ul class="left">
    </ul>
  </section>
</nav>






<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right" style="list-style : none;display: inline-block">
          
        </ul>
      </nav>
    </div>
  </div>
</header> -->
 <!-- <ul>
                    <li> <%= link_to "Profile", current_user  %> </li>
                    <li> <%= link_to "Settings", '#'  %> </li>
                    <li> <%= link_to "Sign out", signout_path, method: "delete" %> </li>
                  </ul> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>


    <link rel="stylesheet" href="http://cdn.jsdelivr.net/foundation/4.3.2/css/foundation.min.css">
   <%= javascript_include_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

     <%= render 'layouts/shim' %> 
  </head>
  <body>
    <%= render 'layouts/header' %> 
    <div class="container">
      <% flash.each do |key, value| %>
        <div style = "color : green"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  
    <h5><%= pluralize(@user.errors.count, "erreur") %>
        ont empêché d'enregistrer votre inscription</h5>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li style = "color: red;"> <%= msg %> </li>
    <% end %>
    </ul>
  
<% end %>

app/views/static_pages/about.html.erb
<center>
	<h1> About us </h1>
</center>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<center> 
	<h1>Contact</h1>
	<p>
  		Contact Ruby on Rails Tutorial about the sample app at the
  		<a href="http://railstutorial.org/contact">contact page</a>.
    </p>
</center>

app/views/static_pages/help.html.erb
<% provide(:title,'Help') %>
<center> <h1>Help</h1></center>

app/views/static_pages/home.html.erb
<div class="row">

  <div class="small-10 columns">
  	<h1> <img alt="Rails" src="/assets/rails.png" /> Welcome to the Sample App</h1>
        <center> <h5>
            This is the home page for the
            <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
            Sample App.
         </h5></center> 
	</div>
	
</div>



<center  > <a style="margin-top: 83px;" class="button [radius round]"  <%= link_to "Sign up now!", signup_path %>    </a></center> 	
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  
    | <%= link_to "delete", user, :method => :delete,
                                  :data => { :confirm => "You sure?" } %>
 
</li>

app/views/users/edit.html.erb
<% provide(:title,"Editer user") %>


  
  <div class="row">
  	<div class="small-4 columns">
     <h3>Update your profile</h3>
	<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	    <%= f.label :name, "Name" %>
	    <%= f.text_field :name %>
		<%= f.label :email, "Email" %>
		<%= f.text_field :email %>
		<%= f.label :password, "Password" %>
		<%= f.password_field :password %>
		<%= f.label :password_confirmation, "Password _Confirmation" %>

		<%= f.password_field :password_confirmation %>
		<%= f.submit "Save change", :disable_with => 'Save changeing...' %> <br> <br>
	
	<%= gravatar_for @user %>
	<a href="http://gravatar.com/emails"> change </a>
  <% end %>
  <p> Pas encore inscrit ? <%= link_to "Sign up now!", signup_path %></p>
  	</div>
  </div>

app/views/users/index.html.erb
<%= provide(:title, 'Tous les utilisateurs') %>
<h3>All users</h3>

<%= render @users %>

app/views/users/new.html.erb
<% provide(:title,'Sign up') %>

<div class="row">
<div class="small-8 columns">
	<center> 
<h1>Sign up </h1>

<%= form_for (@user) do |f| %>
<%= render 'shared/error_messages' %>
	<%= f.label :name, "Name" %>
	<%= f.text_field :name %>
	<%= f.label :email, "Email" %>
	<%= f.text_field :email %>
	<%= f.label :password, "Password" %>
	<%= f.password_field :password %>
	<%= f.label :password_confirmation, "Password _Confirmation" %>	
	<%= f.password_field :password_confirmation %>
	<%= f.submit "Create my account", :disable_with => 'Create my accounting...' %>
		
<% end %>

</center>

</div>
</div>

app/views/users/show.html.erb
<center style="margin-top: 30px; margin-right: 1000px;">
	 <% provide(:title, @user.name) %>
     <%= gravatar_for @user %>
     <%= @user.name %>

   
	</center>